commitizen:
  github_repo: ThimDeveloper/cz-github-linear-conventional
  linear_base_url: https://linear.app/caesari
  name: cz_github_linear_conventional
  tag_format: $version
  version: 1.1.4
  version_files:
  - src/__version__.py
  - setup.py:version
