name: Bump version

on:
  pull_request:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          extra_requirements: "cz-github-linear-conventional"
          commitizen_version: latest
          changelog: false
          push: false
          commit: false
          dry_run: true
      - name: Print Version
        if: ${{ steps.cz.outputs.version }}
        run: echo "cz-github-linear-conventional will be bumped to version ${{ steps.cz.outputs.version }}"
